---
# Image from https://hub.docker.com/_/php/
image: php:7.3

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install -yqq curl git libcurl4-gnutls-dev libxml2-dev libbz2-dev
    libicu-dev libzip-dev wget zlib1g-dev zip automake autoconf libtool g++
  # Install latest ICU version
  - curl -sS -o /tmp/icu.tar.gz -L http://download.icu-project.org/files/icu4c/63.1/icu4c-63_1-src.tgz
  - tar -zxf /tmp/icu.tar.gz -C /tmp
  - cd /tmp/icu/source
  - ./configure --prefix=/usr/local
  - make
  - make install
  - cd -
  # Install PHP extensions
  - docker-php-ext-configure intl --with-icu-dir=/usr/local
  - docker-php-ext-install curl json intl mbstring xml zip
  # Install & enable Xdebug for code coverage reports
  - pecl install xdebug-beta
  - docker-php-ext-enable xdebug
  # Install and run Composer
  - curl -sS https://getcomposer.org/installer | php
  - mv composer.phar /usr/bin/composer
  - composer install

test:php7.3:
  image: php:7.3
  stage: test
  script:
    # composer.json normalization
    #- composer normalize --dry-run --indent-size=1 --indent-style=tab
    # Check if syntax errors was fixed with php-cs-fixer
    #- vendor/bin/php-cs-fixer fix --diff --dry-run --verbose
    # PHP errors
    #- php -l src/*
    #- php -l tests/*
    # Analyse code with PHPStan
    #- vendor/bin/phpstan analyse
    # PHPMD
    #- vendor/bin/phpmd src/ text phpmd.xml
    #- vendor/bin/phpmd tests/ text phpmd.xml
    # Run PHPUnit
    - vendor/bin/phpunit --colors=never
    # ApiGen
    - vendor/bin/apigen generate src --destination build/api/
  artifacts:
    paths:
      - build/coverage/
      - build/api/
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

pages:
  stage: deploy
  dependencies:
    - test:php7.3
  environment:
    name: production
    url: https://the-framework.gitlab.io
  script:
    - mkdir public/
    - mv build/coverage/ public/
    - mv build/api/ public/
  artifacts:
    paths:
      - public
  only:
    - master
